feat: menambahkan materi validation
bellshade/CPP pull request #24
Opened 2021-10-17 21:06 UTC by KimmyKx

## deskripsi (description)

## contributor requirements (syarat contributor) dan lain-lain:

- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

- [x] saya sudah membaca (i have read) [CONTRIBUTING](https://github.com/bellshade/CppAlgorithm/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
- [x] saya menggunakan komentar pada kode secara jelas dan mudah dipahami
- [x] saya menggunakan bahasa indonesia untuk memberikan penjelasan dari kode yang saya buat

## env
saya menggunakan (im used):

- ``os`` = ``linux / windows / macOS``
- ``g++`` = ``g++ --version``

## testing 
- [ ] cmake

2021-10-18 06:41 UTC, KimmyKx commented
> dimohon untuk tidak menggunakan `using namespace std;`.
> 
> tolong tambahkan juga penjelasan di file README.md dan masukkan ke dalam satu folder.
> 
> ```
> └── validation
>     ├── numberValidation
>     │   ├── README.md
>     │   └── numberValidation.cpp
> ```

Ok kak

2021-10-18 08:49 UTC, KimmyKx commented
> Tolong tambahin introduksi dan kegunaan algoritma dalam dokumen markdown dan di dalam source code dalam bentuk comment. Lalu, perhatikan commit message, kita sudah tidak menggunakan `add` sebagai pesan commit yang valid. Trims

baik terima kasih kak

2021-10-27 13:50 UTC, nomadkode commented
Request code review & merge @arifyunando @nuraskiah

2021-11-03 22:38 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Tentu saja pertama yang akan kita lakukan adalah meminta user untuk menginput
Tentu saja pertama yang akan kita lakukan adalah meminta user untuk menginput

perbaiki

Hal pertama pertama yang akan dilakukan adalah meminta user untuk menginput angka

2021-11-03 22:41 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Kemudian disini fungsi utama yang akan jalan
Kemudian disini fungsi utama yang akan jalan

perbaiki

Kemudian ada pengecekan tipe data dari inputan sebelumnya

2021-11-03 22:42 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Kita bisa mengganti `if` menjadi `while` jika ingin inputnya berulang hingga yang di input adalah angka
di input -> diinput

2021-11-03 22:43 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Bersihkan error-error yang ada dalam `cin`-nya agar operasi berikutnya bekerja dengan baik
"... yang ada di dalam ..."

2021-11-03 22:45 UTC, AdhyWiranto44 requested changes

2021-11-03 22:45 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Tentu saja pertama yang akan kita lakukan adalah meminta user untuk menginput
Tentu saja pertama yang akan kita lakukan adalah meminta user untuk menginput

perbaiki

Hal pertama pertama yang akan dilakukan adalah meminta user untuk menginput angka

2021-11-03 22:45 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Kemudian disini fungsi utama yang akan jalan
Kemudian disini fungsi utama yang akan jalan

perbaiki

Kemudian ada pengecekan tipe data dari inputan sebelumnya

2021-11-03 22:45 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Kita bisa mengganti `if` menjadi `while` jika ingin inputnya berulang hingga yang di input adalah angka
di input -> diinput

2021-11-03 22:45 UTC, AdhyWiranto44 commented on validation/numberValidation/README.md
> +Bersihkan error-error yang ada dalam `cin`-nya agar operasi berikutnya bekerja dengan baik
"... yang ada di dalam ..."

2021-11-23 00:53 UTC, slowy07 commented
close karena tidak ada perubahan pada pull request ini

2021-11-23 00:53 UTC, closed without merging