Mape
bellshade/CPP pull request #95
Opened 2023-06-19 07:27 UTC by kayabaakihiko13

# Deskripsi (Description)

# Checklist:
##### Umum:
- [x] Saya menambah algoritma terbaru.
- [ ] Saya memperbaiki algoritma yang sudah ada.
- [ ] Saya memperbaiki dokumentasi.
- [x] Saya menambah dokumentasi.

##### Contributor Requirements (Syarat Kontributor) dan Lain-Lain:
 - [x] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/CPP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
 - [x] Saya telah menambahkan komentar kode yang memberikan penjelasan maksud dari kode yang saya buat.
 - [x] Saya menggunakan bahasa Indonesia untuk memberikan penjelasan dari kode yang saya buat.

# Environment
Saya menggunakan (I'm using):

- ``OS`` = `Linux` 
- ``g++`` = g++ 12.0.0 ubuntu

# Link Issues

Issues : #

2023-06-20 06:02 UTC, slowy07 requested changes
gunakan fungsi dari ampersand dan lakukan reformatting kodenya agar tidak ada blank space

2023-06-20 06:02 UTC, slowy07 commented on math/mean_absolute_percentage_error.cpp
> +double mean_absolute_percentage_error(const std::vector<float>data_predict,const std::vector<float>data_actual){
pakai tanda ampersand
```suggestion
double mean_absolute_percentage_error(const std::vector<float>& data_predict, const std::vector<float>& data_actual){
```

2023-06-21 14:50 UTC, kayabaakihiko13 commented
> gunakan ampersand dan lakukan reformatting kodenya agar tidak ada blank space

bang arfy,refensi tentang merge itu yang konflik gimana?
aku lupa taro mana refensinya

2023-06-24 12:31 UTC, slowy07 approved these changes
LGTM, terima kasih atas kontribusinya @kayabaakihiko13 !

2023-06-24 12:31 UTC, merged